title: "Sample Documentation"
description: "A sample site using the Minimal Mistakes Jekyll theme."
url: "https://wistfulflare.github.io/test"
baseurl: "" # Leave blank unless your site is in a subdirectory

# Theme setup
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Build settings
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed

# Defaults for posts and pages
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      toc: true
      toc_sticky: true

# Exclude files from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Optional: Author profile on the sidebar
author:
  name: "Your Name"
  avatar: "/assets/images/avatar.png"
  bio: "Short bio goes here."